name: "insulator_yolo_pre_640"
backend: "python"
max_batch_size: 0

input [
  { name: "jpeg" data_type: TYPE_STRING dims: [ 1 ] }
]

output [
  { name: "images" data_type: TYPE_FP32 dims: [ 1, 3, 640, 640 ] },
  { name: "meta"   data_type: TYPE_FP32 dims: [ 1, 5 ] }
]
