name: "insulator_yolo"
platform: "tensorrt_plan"
max_batch_size: 8

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 1280, 1280]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [33600, 68]
  }
]

instance_group [
  { kind: KIND_GPU, count: 1 }
]

